name: ci-flow

on:
  push:
    tags-ignore:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            profile: linux
          - imageName: 'macOS-10.14'
            target: x86_64-apple-darwin
            profile: mac
          - imageName: 'windows-2019'
            target: x86_64-pc-windows-msvc
            profile: windows

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust_toolchain }}
    - uses: actions/checkout@v1
    - name: Setup cargo-make
      run: |
        cargo install cargo-make
        cargo make debug
    - name: Run tests
      run: cargo make --disable-check-for-updates --profile ${{ matrix.os.profile }} --env TARGET=${{matrix.os.target}} ci-flow
