name: release-flow

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# on:
#   release:
#     types: [published]

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
            profile: linux
          - imageName: 'macOS-10.14'
            target: x86_64-apple-darwin
            profile: mac
          - imageName: 'windows-2019'
            target: x86_64-pc-windows-msvc
            profile: windows

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust_toolchain }}
    - uses: actions/checkout@v1
    - name: Setup cargo-make
      run: cargo install cargo-make
    - name: Make zip-release-ci-flow
      run: cargo make --disable-check-for-updates --profile ${{ matrix.os.profile }} --env TARGET=${{matrix.os.target}} zip-release-ci-flow
    - name: Upload to gitHub release
      run: cargo make --disable-check-for-updates --profile ${{ matrix.os.profile }} --env TARGET=${{matrix.os.target}} github-upload-flow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
